version: '3.1'
services:

  db: 
    container_name: db_projet_8
    image: mysql:5
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'symfony'
      MYSQL_PASSWORD: 'root'
      MYSQL_USER: 'user'
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
